repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: backend-check
        name: Backend Check (check, clippy, format)
        language: system
        entry: cargo check && cargo clippy --all-targets --all-features -- -D warnings && cargo fmt --all -- --check

      - id: frontend-check
        name: Frontend Check (type-check, lint, format)
        language: system
        entry: pnpm run check
        pass_filenames: false
